#:schema https://dystroy.org/bacon/.bacon.schema.json

# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

env.CARGO_TERM_COLOR = "always"

[jobs.dev]
command = ["./dev.sh"]
watch = ["./src", "./javascript/src"]
need_stdout = false
